id: P5F11104F
initial_creation_type: ocr
source_metadata:
  volumes:
    1018737ffb904a4ea202504ffe6fdcb5:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: འཕགས་པ་སྒོ་དྲུག་པའི་གཟུངས་ཀྱི་རྣམ་པར་བཤད་པ།
      total_pages: 1498
      volume_number: 65
